/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.toscadsl.ui.internal.ToscadslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ToscaDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ToscadslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ToscadslActivator.getInstance().getInjector(ToscadslActivator.ORG_XTEXT_EXAMPLE_MYDSL_TOSCADSL);
	}
	
}
